version: '3.8'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: prueba
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 

  web:
    build: .
    command: flask run --host=0.0.0.0
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      FLASK_APP: main.py
      SQLALCHEMY_DATABASE_URI: postgresql://root:root@db:5432/prueba

volumes:
  postgres_data:
